/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.Enterprise;
import Business.KitchenSystem;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.VolunteerOrganization;
import Business.Person.Person;
import Validator.MyDigitInputVerifier;
import Validator.MyEmailInputVerifier;
import Validator.MyStringInputVerifier;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sumit
 */
public class VolunteerSignUpJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    private final JPanel userProcessContainer;
    private final KitchenSystem system;
    private final DB4OUtil dB4OUtil;
    public VolunteerSignUpJPanel(JPanel userProcessContainer, KitchenSystem system, DB4OUtil dB4OUtil) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        this.dB4OUtil = dB4OUtil;
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(new Date());
        comboDateChooser.setMaxDate(calendar);

        txtName.setInputVerifier(new MyStringInputVerifier());
        txtAddress.setInputVerifier(new MyStringInputVerifier());
        txtPhoneNumber.setInputVerifier(new MyDigitInputVerifier());
        txtEmailAddress.setInputVerifier(new MyEmailInputVerifier());
        populateCityCombo();
        DisplayImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSignUp = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblAddress1 = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblEmailID = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnSignUp = new javax.swing.JButton();
        comboDateChooser = new datechooser.beans.DateChooserCombo();
        txtEmailAddress = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        comboCity = new javax.swing.JComboBox();
        txtAddress = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        lblicon = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));

        lblSignUp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSignUp.setText("Volunteer Signup Form");

        lblName.setText("Name:");

        lblAddress.setText("Address:");

        lblAddress1.setText("Signing up for:");

        lblPhoneNumber.setText("Phone Number:");

        lblEmailID.setText("Email Address (Gmail Only):");

        lblDOB.setText("Date Of Birth:");

        jLabel1.setText("Note: You should be more than 18 years old to sign up for volunteering.");

        btnSignUp.setBackground(new java.awt.Color(255, 255, 204));
        btnSignUp.setText("Sign Me Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        comboDateChooser.setCurrentView(new datechooser.view.appearance.AppearancesList("Swing",
            new datechooser.view.appearance.ViewAppearance("custom",
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    true,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 255),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(128, 128, 128),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(0, 0, 255),
                    false,
                    true,
                    new datechooser.view.appearance.swing.LabelPainter()),
                new datechooser.view.appearance.swing.SwingCellAppearance(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11),
                    new java.awt.Color(0, 0, 0),
                    new java.awt.Color(255, 0, 0),
                    false,
                    false,
                    new datechooser.view.appearance.swing.ButtonPainter()),
                (datechooser.view.BackRenderer)null,
                false,
                true)));
    comboDateChooser.setCalendarBackground(new java.awt.Color(255, 204, 51));
    comboDateChooser.setCalendarPreferredSize(new java.awt.Dimension(350, 240));
    comboDateChooser.setNothingAllowed(false);
    comboDateChooser.setNavigateFont(new java.awt.Font("Tahoma", java.awt.Font.PLAIN, 11));
    comboDateChooser.setShowOneMonth(true);

    txtEmailAddress.setBackground(new java.awt.Color(255, 255, 204));

    txtPhoneNumber.setBackground(new java.awt.Color(255, 255, 204));

    comboCity.setBackground(new java.awt.Color(255, 255, 204));

    txtAddress.setBackground(new java.awt.Color(255, 255, 204));

    txtName.setBackground(new java.awt.Color(255, 255, 204));

    lblicon.setBackground(new java.awt.Color(255, 255, 255));
    lblicon.setText("jLabel2");

    jSeparator1.setBackground(new java.awt.Color(255, 204, 51));
    jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(lblSignUp))
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(157, 157, 157)
                            .addComponent(btnSignUp, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(38, 38, 38)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblAddress)
                            .addComponent(lblEmailID)
                            .addComponent(lblDOB)
                            .addComponent(lblAddress1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(comboDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(comboCity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblPhoneNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(lblicon, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(18, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblicon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblSignUp)
                            .addGap(22, 22, 22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblName)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(27, 27, 27)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblAddress)
                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(21, 21, 21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblAddress1)
                                .addComponent(comboCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(19, 19, 19)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPhoneNumber)
                                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblEmailID)
                                .addComponent(txtEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblDOB)
                                .addComponent(comboDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(btnSignUp)
                            .addGap(0, 165, Short.MAX_VALUE)))
                    .addContainerGap())))
    );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        if (txtName.getText().isEmpty()) {
            return;
        }
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(new Date());
        Calendar selectedDate = comboDateChooser.getSelectedDate();
        long days = daysBetween(selectedDate, calendar);
        if (days < 365 * 18) {
            JOptionPane.showMessageDialog(this, "You need to be 18+ to register for Volunteering.",
                    "Warning", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        //Person participant = system.getParticipantList().createParticipant();
        //Participant should be added in enterprise not in network
        Person participant = null;
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseList().getEnterpriseList()) {
                if (((String) comboCity.getSelectedItem()).equalsIgnoreCase(enterprise.getName())) {
                    for (Organization organization : enterprise.getOrganizationList().getOrganizationList()) {
                        if (organization instanceof VolunteerOrganization) {
                            participant = organization.getParticipantList().createParticipant(txtName.getText());
                            break;
                        }
                    }
                }
            }
        }
        if (participant == null) {
            return;
        }
        participant.setAge((int) days / 365);
        participant.setDob(selectedDate.getTime());
        participant.setAddress(txtAddress.getText());
        participant.setCity(comboCity.getSelectedItem().toString());
        participant.setEmailID(txtEmailAddress.getText());
        participant.setPhonenumber(txtPhoneNumber.getText());
        participant.setDesignation("Volunteer");
        JOptionPane.showMessageDialog(this, "You Have Signed Up successfully. "
                + "Please refer your mail after few hours for further Details.", "Information", JOptionPane.INFORMATION_MESSAGE);
        comboDateChooser.setCurrent(calendar);
        dB4OUtil.storeSystem(system);
        txtName.setText("");
        txtAddress.setText("");
        txtPhoneNumber.setText("");
        txtEmailAddress.setText("");
        
    }//GEN-LAST:event_btnSignUpActionPerformed

    private long daysBetween(Calendar startDate, Calendar endDate) {
        Calendar date = (Calendar) startDate.clone();
        long daysBetween = 0;
        while (date.before(endDate)) {
            date.add(Calendar.DAY_OF_MONTH, 1);
            daysBetween++;
        }
        return daysBetween;
    }

    private void populateCityCombo() {
        comboCity.removeAllItems();
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseList().getEnterpriseList()) {
                comboCity.addItem(enterprise.getName());
            }
        }
    }
    
    private void DisplayImage() {
        try {
            BufferedImage img=ImageIO.read(new File("resources//community-kitchen.jpg"));
            ImageIcon icon=new ImageIcon(img);
            lblicon.setIcon(icon);   
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSignUp;
    private javax.swing.JComboBox comboCity;
    private datechooser.beans.DateChooserCombo comboDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblEmailID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblSignUp;
    private javax.swing.JLabel lblicon;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtEmailAddress;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
