/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ChefRole;

import Business.Enterprise.Enterprise;
import Business.JobQueue.ScheduledEventPost;
import Business.JobQueue.TaskPost;
import Business.Organization.ChefOrganization;
import Business.Organization.Organization;
import Business.Organization.VolunteerOrganization;
import Business.Person.Person;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sumit
 */
public class AssignCookingChoresJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AssignCookingChoresJPanel
     */
    private final ChefOrganization chefOrg;
    private final JPanel userProcessContainer;
    private final UserAccount userAccount;
    private final Person person;
    private final Enterprise enterprise;
    private final ScheduledEventPost event;

    public AssignCookingChoresJPanel(JPanel userProcessContainer, ChefOrganization chefOrg,
            Person person, UserAccount userAccount, Enterprise enterprise, ScheduledEventPost event) {
        this.person = person;
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.chefOrg = chefOrg;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.event = event;
        if (person != null) {
            txtParticipantAge.setText(String.valueOf(person.getAge()));
            txtParticipantName.setText(person.getName());
        } else {
            txtParticipantAge.setEditable(false);
            txtParticipantName.setEditable(false);
            txtParticipantAge.setEnabled(false);
            txtParticipantName.setEnabled(false);
            btnAssign.setText("Post Task");
            this.remove(txtParticipantAge);
            this.remove(txtParticipantName);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtParticipantName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtParticipantAge = new javax.swing.JTextField();
        comboTaskStatus = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTaskAssigned = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTaskDesc = new javax.swing.JTextArea();
        btnAssign = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        txtParticipantName.setEditable(false);
        txtParticipantName.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setText("Partcipant Name:");

        jLabel2.setText("Participant Age:");

        txtParticipantAge.setEditable(false);
        txtParticipantAge.setBackground(new java.awt.Color(255, 255, 204));

        if (person != null) {
            comboTaskStatus.setBackground(new java.awt.Color(255, 255, 204));
            comboTaskStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Assigned", "In Progress" }));
        } else {
            comboTaskStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not Assigned"}));
        }

        jLabel3.setText("Task:");

        jLabel4.setText("Task Status:");

        txtTaskAssigned.setBackground(new java.awt.Color(255, 255, 204));

        jLabel5.setText("Task Description:");

        txtTaskDesc.setBackground(new java.awt.Color(255, 255, 204));
        txtTaskDesc.setColumns(20);
        txtTaskDesc.setRows(5);
        jScrollPane1.setViewportView(txtTaskDesc);

        btnAssign.setBackground(new java.awt.Color(255, 255, 204));
        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 204));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Assign Cooking Tasks");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtParticipantAge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                                    .addComponent(txtParticipantName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTaskAssigned)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnBack)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAssign))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4))
                                    .addGap(99, 99, 99)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane1)
                                        .addComponent(comboTaskStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel6)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtParticipantName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtParticipantAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTaskAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboTaskStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAssign)
                    .addComponent(btnBack))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        TaskPost job = new TaskPost();
        UserAccount ua = null;
        for (Organization org : enterprise.getOrganizationList().getOrganizationList()) {
            if (org instanceof VolunteerOrganization) {
                for (UserAccount user : org.getUserAccountList().getUserAccountList()) {
                    if (person != null && user.getParticipant().equals(person)) {
                        job.setReceiver(user);
                        ua = user;
                        break;
                    }
                }
            } 
        }
        job.setSender(userAccount);
        job.setVolunteerTask(txtTaskAssigned.getText());
        job.setMessage(txtTaskDesc.getText());
        job.setStatus(comboTaskStatus.getSelectedItem().toString());
        job.setTaskRequestDate(event.getTaskScheduleDate());
        if (event.getTaskScheduleDate().after(new Date())) {
            job.setTaskScheduleDate(event.getTaskScheduleDate());                    
        }
        if (ua != null) {
            ua.getJobQueue().getJobRequestList().add(job);
            JOptionPane.showMessageDialog(this, "Volunteer is assigned to work successfully",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
            chefOrg.getJobQueue().getJobRequestList().add(job);
            JOptionPane.showMessageDialog(this, "Task is posted successfully",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        txtParticipantAge.setText("");
        txtParticipantName.setText("");
        txtTaskAssigned.setText("");
        txtTaskDesc.setText("");
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageCookingChoresJPanel mccjp = (ManageCookingChoresJPanel) component;
        mccjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox comboTaskStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtParticipantAge;
    private javax.swing.JTextField txtParticipantName;
    private javax.swing.JTextField txtTaskAssigned;
    private javax.swing.JTextArea txtTaskDesc;
    // End of variables declaration//GEN-END:variables
}
