/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ChefRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.KitchenEnterprise;
import Business.JobQueue.JobRequest;
import Business.JobQueue.ScheduledEventPost;
import Business.MenuDishes.MenuType;
import Business.Organization.ChefOrganization;
import Business.Organization.CoordinatorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import UserInterface.ComposeEmailJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sumit
 */
public class ChefWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChefWorkAreaJPanel
     */
    private final JPanel userProcessContainer;
    private final UserAccount userAccount;
    private final ChefOrganization chefOrg;
    private final Enterprise enterprise;

    public ChefWorkAreaJPanel(JPanel upc, UserAccount ua, ChefOrganization org, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = upc;
        this.userAccount = ua;
        this.chefOrg = org;
        this.enterprise = enterprise;
        populateTable();
        lblName.setText(ua.getParticipant().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEvents = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnManageMenu = new javax.swing.JButton();
        btnManageCookingTask = new javax.swing.JButton();
        btnSendEmail = new javax.swing.JButton();
        lblName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tblEvents.setBackground(new java.awt.Color(255, 255, 204));
        tblEvents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Event Name", "Event Date", "Event Status", "Event Menu"
            }
        ));
        jScrollPane1.setViewportView(tblEvents);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Welcome Kitchen Chef");

        btnManageMenu.setBackground(new java.awt.Color(255, 255, 204));
        btnManageMenu.setText("Manage Menu");
        btnManageMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageMenuActionPerformed(evt);
            }
        });

        btnManageCookingTask.setBackground(new java.awt.Color(255, 255, 204));
        btnManageCookingTask.setText("Manage Cooking Chores");
        btnManageCookingTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCookingTaskActionPerformed(evt);
            }
        });

        btnSendEmail.setBackground(new java.awt.Color(255, 255, 204));
        btnSendEmail.setText("Send Email");
        btnSendEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendEmailActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblName.setText("<<WelCome >>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnSendEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageCookingTask, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblName)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblName))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageMenu)
                .addGap(18, 18, 18)
                .addComponent(btnManageCookingTask)
                .addGap(18, 18, 18)
                .addComponent(btnSendEmail)
                .addContainerGap(37, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendEmailActionPerformed
        // TODO add your handling code here:
        ComposeEmailJPanel frame = new ComposeEmailJPanel(userProcessContainer, userAccount, enterprise);
        userProcessContainer.add("ComposeEmailJPanel", frame);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSendEmailActionPerformed

    private void btnManageCookingTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCookingTaskActionPerformed
        // TODO add your handling code here:
        int row_selected = tblEvents.getSelectedRow();
        if (row_selected < 0) {
            JOptionPane.showMessageDialog(this, "Please select an event to add tasks into.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        ManageCookingChoresJPanel cookingChores = new ManageCookingChoresJPanel(userProcessContainer,
                chefOrg, userAccount, enterprise, (ScheduledEventPost) tblEvents.getValueAt(row_selected, 0));
        userProcessContainer.add("ManageCookingChoresJPanel", cookingChores);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageCookingTaskActionPerformed

    private void btnManageMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageMenuActionPerformed
        // TODO add your handling code here:
        int row_selected = tblEvents.getSelectedRow();
        if (row_selected < 0) {
            JOptionPane.showMessageDialog(this, "Please select an event to add Menu.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        ManageMenuJPanel menu = new ManageMenuJPanel(userProcessContainer, chefOrg, (KitchenEnterprise) enterprise,
                (ScheduledEventPost) tblEvents.getValueAt(row_selected, 0));
        userProcessContainer.add("ManageMenuJPanel", menu);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageMenuActionPerformed

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblEvents.getModel();
        model.setRowCount(0);

        for (Organization organization : enterprise.getOrganizationList().getOrganizationList()) {

            if (organization instanceof CoordinatorOrganization) {
                for (JobRequest post : organization.getJobQueue().getJobRequestList()) {
                    Object row[] = new Object[4];
                    ScheduledEventPost event = (ScheduledEventPost) post;
                    row[0] = event;
                    row[1] = new java.text.SimpleDateFormat("MM/dd/yyyy").format(event.getTaskScheduleDate());
                    row[2] = event.getStatus();
                    row[3] = getMenuList(event);
                    model.addRow(row);
                }
                break;
            }
        }

    }
    
    private String getMenuList(ScheduledEventPost event) {
        String list = "";
        int i = 1;
        for (MenuType menu : event.getMenuList().getMenuList()) {
            list += menu.getFoodType();
            if (event.getMenuList().getMenuList().size() > i) {
                list += ", ";
            }            
            i++; 
        }
        return list;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageCookingTask;
    private javax.swing.JButton btnManageMenu;
    private javax.swing.JButton btnSendEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JTable tblEvents;
    // End of variables declaration//GEN-END:variables
}
