/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ChefRole;

import Business.Enterprise.KitchenEnterprise;
import Business.GroceryItems.GroceryItem;
import Business.JobQueue.ScheduledEventPost;
import Business.MenuDishes.MenuDish;
import Business.MenuDishes.MenuType;
import Business.Organization.ChefOrganization;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sumit
 */
public class ManageMenuJPanel extends javax.swing.JPanel {

    private final ChefOrganization chefOrg;
    private final JPanel userProcessContainer;
    private final KitchenEnterprise enterprise;
    private final ScheduledEventPost event;

    /**
     * Creates new form ManageMenuJPanel
     */
    public ManageMenuJPanel(JPanel userProcessContainer, ChefOrganization chefOrg, KitchenEnterprise enterprise,
            ScheduledEventPost event) {
        initComponents();
        this.chefOrg = chefOrg;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.event = event;
        populateGroceryTable();
        populateDishTable((String) comboMenuName.getSelectedItem());
    }

    private void populateDishTable(String menu) {
        DefaultTableModel model = (DefaultTableModel) tblMenuItems.getModel();
        model.setRowCount(0);

        for (MenuType type : event.getMenuList().getMenuList()) {
            if (menu.equalsIgnoreCase(type.toString())) {
                for (MenuDish dish : type.getCatalog().getDishList()) {
                    Object row[] = new Object[4];
                    row[0] = dish;
                    row[1] = dish.getDishType();
                    row[2] = dish.getDishDescription();
                    row[3] = dish.getDishTaste();
                    model.addRow(row);
                }
                break;
            }
        }
    }

    private void populateGroceryTable() {
        DefaultTableModel model = (DefaultTableModel) tblGrocery.getModel();
        model.setRowCount(0);

        for (GroceryItem item : enterprise.getGroceryList().getItemList()) {
            Object row[] = new Object[3];
            row[0] = item;
            row[1] = item.getQuantity();
            row[2] = item.getItemNote();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblGrocery = new javax.swing.JTable();
        comboMenuName = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMenuItems = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtDishName = new javax.swing.JTextField();
        txtDishDesc = new javax.swing.JTextField();
        txtDishTaste = new javax.swing.JTextField();
        btnAddDish = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        comboDishType = new javax.swing.JComboBox();
        btnRemoveDish = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tblGrocery.setBackground(new java.awt.Color(255, 255, 204));
        tblGrocery.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Grocery Name", "Grocery Quantity", "Grocery Description"
            }
        ));
        jScrollPane1.setViewportView(tblGrocery);

        comboMenuName.setBackground(new java.awt.Color(255, 255, 204));
        comboMenuName.setModel(new javax.swing.DefaultComboBoxModel(new
            String[] { "Indian", "American", "Continental", "Chinese",
                "Barbeque Grilled", "Italian", "Meditarranean" }));
    comboMenuName.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            comboMenuNameActionPerformed(evt);
        }
    });

    jLabel1.setText("Menu:");

    tblMenuItems.setBackground(new java.awt.Color(255, 255, 204));
    tblMenuItems.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Dish Name", "Dish Type", "Dish Description", "Dish Taste"
        }
    ));
    jScrollPane2.setViewportView(tblMenuItems);
    if (tblMenuItems.getColumnModel().getColumnCount() > 0) {
        tblMenuItems.getColumnModel().getColumn(1).setResizable(false);
    }

    jLabel2.setText("Dish Name:");

    jLabel3.setText("Dish Type:");

    jLabel4.setText("Dish Description:");

    jLabel5.setText("Dish Taste:");

    txtDishName.setBackground(new java.awt.Color(255, 255, 204));

    txtDishDesc.setBackground(new java.awt.Color(255, 255, 204));

    txtDishTaste.setBackground(new java.awt.Color(255, 255, 204));

    btnAddDish.setBackground(new java.awt.Color(255, 255, 204));
    btnAddDish.setText("Add Dish");
    btnAddDish.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAddDishActionPerformed(evt);
        }
    });

    btnBack.setBackground(new java.awt.Color(255, 255, 204));
    btnBack.setText("<< Back");
    btnBack.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnBackActionPerformed(evt);
        }
    });

    jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel6.setText("Manage Menu:");

    comboDishType.setBackground(new java.awt.Color(255, 255, 204));
    comboDishType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vegetarian", "Non-Vegetarian", "Vegan" }));

    btnRemoveDish.setBackground(new java.awt.Color(255, 255, 204));
    btnRemoveDish.setText("Remove Dish");
    btnRemoveDish.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnRemoveDishActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(layout.createSequentialGroup()
                    .addGap(146, 146, 146)
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addComponent(comboMenuName, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(jLabel6)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(btnBack)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4))
                    .addGap(66, 66, 66)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtDishName, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDishDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDishTaste, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddDish, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboDishType, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemoveDish)
                    .addGap(8, 8, 8))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                .addComponent(jScrollPane2))
            .addContainerGap(241, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(21, 21, 21)
            .addComponent(jLabel6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(13, 13, 13)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(comboMenuName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(txtDishName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnRemoveDish))
            .addGap(25, 25, 25)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(comboDishType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(txtDishDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel5)
                .addComponent(txtDishTaste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnBack)
                .addComponent(btnAddDish))
            .addContainerGap(90, Short.MAX_VALUE))
    );
    }// </editor-fold>//GEN-END:initComponents

    private void comboMenuNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMenuNameActionPerformed
        // TODO add your handling code here:
        String menu = (String) comboMenuName.getSelectedItem();
        populateDishTable(menu);
    }//GEN-LAST:event_comboMenuNameActionPerformed

    private void btnAddDishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDishActionPerformed
        // TODO add your handling code here:
        if (txtDishName.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Dish Name can not be empty", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String menu = (String) comboMenuName.getSelectedItem();
        MenuType mainType = null;
        boolean isAlreadyPresent = false;
        for ( MenuType type : event.getMenuList().getMenuList()) {
            if (type.getFoodType().equalsIgnoreCase(menu)) {              
                mainType = type;
                isAlreadyPresent = true;
                break;
            }
        }
        if (! isAlreadyPresent) {
            mainType = event.getMenuList().AddItemtoMenuType();
            mainType.setFoodType(menu);
        }
        
        MenuDish dish = mainType.getCatalog().AddItemtoMenu();
        dish.setDishName(txtDishName.getText());
        dish.setDishTaste(txtDishTaste.getText());
        dish.setDishType(comboDishType.getSelectedItem().toString());
        dish.setDishDescription(txtDishDesc.getText());
        populateDishTable(menu);
        JOptionPane.showMessageDialog(this, "Dish added successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
        txtDishName.setText("");
        txtDishTaste.setText("");
        txtDishDesc.setText("");
    }//GEN-LAST:event_btnAddDishActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ChefWorkAreaJPanel cwajp = (ChefWorkAreaJPanel) component;
        cwajp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRemoveDishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveDishActionPerformed
        // TODO add your handling code here:
        int selected_row = tblMenuItems.getSelectedRow();
        if (selected_row < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Dish to delete from table",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        MenuDish dish = (MenuDish) tblMenuItems.getValueAt(selected_row, 0);
        String menu = (String) comboMenuName.getSelectedItem();
        int dialog_result = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete " + dish.getDishName()
                + " ?","Warning", JOptionPane.YES_NO_OPTION);
        if (dialog_result == JOptionPane.YES_OPTION) {
            for (MenuType type : event.getMenuList().getMenuList()) {
                if (menu.equalsIgnoreCase(type.toString())) {
                    type.getCatalog().removeDish(dish);
                }
            }
            populateDishTable(menu);
            JOptionPane.showMessageDialog(this, "Dish deleted successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
        }       
    }//GEN-LAST:event_btnRemoveDishActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDish;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRemoveDish;
    private javax.swing.JComboBox comboDishType;
    private javax.swing.JComboBox comboMenuName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblGrocery;
    private javax.swing.JTable tblMenuItems;
    private javax.swing.JTextField txtDishDesc;
    private javax.swing.JTextField txtDishName;
    private javax.swing.JTextField txtDishTaste;
    // End of variables declaration//GEN-END:variables
}
