/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CoordinatorRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.KitchenEnterprise;
import Business.JobQueue.JobRequest;
import Business.JobQueue.ScheduledEventPost;
import Business.MenuDishes.MenuType;
import Business.Organization.CoordinatorOrganization;
import Business.Organization.Organization;
import Business.Organization.VolunteerOrganization;
import Business.UserAccount.UserAccount;
import UserInterface.ComposeEmailJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sumit
 */
public class CoordinatorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChefWorkAreaJPanel
     */
    private final JPanel userProcessContainer;
    private final UserAccount userAccount;
    private final CoordinatorOrganization coordOrg;
    private final Enterprise enterprise;

    public CoordinatorWorkAreaJPanel(JPanel upc, UserAccount ua, CoordinatorOrganization org, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = upc;
        this.userAccount = ua;
        this.coordOrg = org;
        this.enterprise = enterprise;
        populateTable();
        lblName.setText(ua.getParticipant().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEvents = new javax.swing.JTable();
        btnEventSchedule = new javax.swing.JButton();
        btnManageGrocery = new javax.swing.JButton();
        btnManageVolunteers = new javax.swing.JButton();
        btnSendEmail = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tblEvents.setBackground(new java.awt.Color(255, 255, 204));
        tblEvents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Event Name", "Event Date", "Event Status", "Event Menu", "Members Attending"
            }
        ));
        jScrollPane1.setViewportView(tblEvents);
        if (tblEvents.getColumnModel().getColumnCount() > 0) {
            tblEvents.getColumnModel().getColumn(4).setResizable(false);
        }

        btnEventSchedule.setBackground(new java.awt.Color(255, 255, 204));
        btnEventSchedule.setText("Schedule New Event");
        btnEventSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventScheduleActionPerformed(evt);
            }
        });

        btnManageGrocery.setBackground(new java.awt.Color(255, 255, 204));
        btnManageGrocery.setText("Manage Grocery Items");
        btnManageGrocery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageGroceryActionPerformed(evt);
            }
        });

        btnManageVolunteers.setBackground(new java.awt.Color(255, 255, 204));
        btnManageVolunteers.setText("Manage Volunteers");
        btnManageVolunteers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageVolunteersActionPerformed(evt);
            }
        });

        btnSendEmail.setBackground(new java.awt.Color(255, 255, 204));
        btnSendEmail.setText("Send Email");
        btnSendEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendEmailActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Welcome Kitchen Coordinator:");

        lblName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblName.setText("<<WelCome >>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblName))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnSendEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageVolunteers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEventSchedule, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageGrocery, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(186, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblName))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEventSchedule)
                .addGap(18, 18, 18)
                .addComponent(btnManageGrocery)
                .addGap(18, 18, 18)
                .addComponent(btnManageVolunteers)
                .addGap(18, 18, 18)
                .addComponent(btnSendEmail)
                .addContainerGap(180, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendEmailActionPerformed
        // TODO add your handling code here:
        ComposeEmailJPanel frame = new ComposeEmailJPanel(userProcessContainer, userAccount, enterprise);
        userProcessContainer.add("ComposeEmailJPanel", frame);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSendEmailActionPerformed

    private void btnManageVolunteersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageVolunteersActionPerformed
        // TODO add your handling code here:
        VolunteerUserAccountJPanel vuajp = null;
        for (Organization organization : enterprise.getOrganizationList().getOrganizationList()) {
            if (organization instanceof VolunteerOrganization) {
                vuajp = new VolunteerUserAccountJPanel(userProcessContainer,
                        (VolunteerOrganization) organization, (KitchenEnterprise) enterprise, userAccount);
                break;
            }
        }
        userProcessContainer.add("VolunteerUserAccountJPanel", vuajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageVolunteersActionPerformed

    private void btnEventScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventScheduleActionPerformed
        // TODO add your handling code here:
        ScheduleEventsJPanel sejp = new ScheduleEventsJPanel(userProcessContainer, userAccount, coordOrg, enterprise);
        userProcessContainer.add("ScheduleEventsJPanel", sejp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnEventScheduleActionPerformed

    private void btnManageGroceryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageGroceryActionPerformed
        // TODO add your handling code here:
        ManageGroceryItemsJPanel mgijp = new ManageGroceryItemsJPanel(userProcessContainer, coordOrg,
                (KitchenEnterprise) enterprise);
        userProcessContainer.add("ManageGroceryItemsJPanel", mgijp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageGroceryActionPerformed

    public void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblEvents.getModel();
        model.setRowCount(0);

        for (JobRequest request : coordOrg.getJobQueue().getJobRequestList()) {
            Object row[] = new Object[5];
            ScheduledEventPost event = (ScheduledEventPost) request;
            row[0] = event;
            row[1] = new java.text.SimpleDateFormat("MM/dd/yyyy").format(request.getTaskScheduleDate());
            row[2] = event.getStatus();
            row[3] = getMenuList(event);
            row[4] = 2 + event.getAttendanceList().size();
            model.addRow(row);
        }
    }

    private String getMenuList(ScheduledEventPost event) {
        String list = "";
        int i = 1;
        for (MenuType menu : event.getMenuList().getMenuList()) {
            list += menu.getFoodType();
            if (event.getMenuList().getMenuList().size() > i) {
                list += ", ";
            }
            i++;
        }
        return list;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEventSchedule;
    private javax.swing.JButton btnManageGrocery;
    private javax.swing.JButton btnManageVolunteers;
    private javax.swing.JButton btnSendEmail;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName;
    private javax.swing.JTable tblEvents;
    // End of variables declaration//GEN-END:variables
}
