/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CoordinatorRole;

import Business.Enterprise.KitchenEnterprise;
import Business.GroceryItems.GroceryItem;
import Business.Organization.CoordinatorOrganization;
import Validator.MyDigitInputVerifier;
import Validator.MyStringInputVerifier;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sumit
 */
public class ManageGroceryItemsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MasterMenuItemsJPanel
     */
    private final JPanel userProcessContainer;
    private final CoordinatorOrganization coordOrg;
    private final KitchenEnterprise enterprise;
    public ManageGroceryItemsJPanel(JPanel userProcessContainer, CoordinatorOrganization coordOrg,
            KitchenEnterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.coordOrg = coordOrg;
        this.enterprise = enterprise;
        populateTable();
        txtItemDesc.setInputVerifier(new MyStringInputVerifier());
        txtItemName.setInputVerifier(new MyStringInputVerifier());
        txtQuantity.setInputVerifier(new MyDigitInputVerifier());
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblGrocery.getModel();
        model.setRowCount(0);

        for (GroceryItem item : enterprise.getGroceryList().getItemList()) {
             Object row[] = new Object[3];
             row[0] = item;
             row[1] = item.getQuantity();
             row[2] = item.getItemNote();
             model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGrocery = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtItemDesc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnDelItem = new javax.swing.JButton();
        btnGetSuppliesInfo = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        btnAddItem.setBackground(new java.awt.Color(255, 255, 204));
        btnAddItem.setText("Add Item");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        tblGrocery.setBackground(new java.awt.Color(255, 255, 204));
        tblGrocery.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Grocery Name", "Grocery Qty. (lbs/ltr)", "Container Capacity(lbs/ltr)", "Grocery Description"
            }
        ));
        jScrollPane1.setViewportView(tblGrocery);

        btnBack.setBackground(new java.awt.Color(255, 255, 204));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setText("Grocery Name:");

        jLabel2.setText("Quantity (lbs/ltr):");

        jLabel3.setText("Grocery Description:");

        txtItemName.setBackground(new java.awt.Color(255, 255, 204));

        txtQuantity.setBackground(new java.awt.Color(255, 255, 204));

        txtItemDesc.setBackground(new java.awt.Color(255, 255, 204));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Manage Grocery Items");

        btnDelItem.setBackground(new java.awt.Color(255, 255, 204));
        btnDelItem.setText("Remove Item");
        btnDelItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelItemActionPerformed(evt);
            }
        });

        btnGetSuppliesInfo.setBackground(new java.awt.Color(255, 255, 204));
        btnGetSuppliesInfo.setText("Get Supplies Info");
        btnGetSuppliesInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetSuppliesInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtItemDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtQuantity, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtItemName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAddItem))
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnGetSuppliesInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGetSuppliesInfo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnDelItem))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtItemDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddItem)
                    .addComponent(btnBack))
                .addContainerGap(122, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        // TODO add your handling code here:
        GroceryItem item = enterprise.getGroceryList().AddItemtoGrocery();
        item.setItemName(txtItemName.getText());
        item.setItemNote(txtItemDesc.getText());
        item.setQuantity(Integer.parseInt(txtQuantity.getText()));
        populateTable();
        JOptionPane.showMessageDialog(this,"Item added successfully","Information", JOptionPane.INFORMATION_MESSAGE);
        txtItemDesc.setText("");
        txtItemName.setText("");
        txtQuantity.setText("");
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDelItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelItemActionPerformed
        // TODO add your handling code here:
        int selected_row = tblGrocery.getSelectedRow();
        if (selected_row < 0) {
            JOptionPane.showMessageDialog(this, "Please select an item to remove.",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        GroceryItem item = (GroceryItem) tblGrocery.getValueAt(selected_row, 0);
        int dialog_result = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete " + item.getItemName()
                + " ?","Warning", JOptionPane.YES_NO_OPTION);
        
        if (dialog_result == JOptionPane.YES_OPTION) {
            enterprise.getGroceryList().RemoveGroceryItem(item);
            populateTable();
            JOptionPane.showMessageDialog(this, "Item deleted successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDelItemActionPerformed

    private void btnGetSuppliesInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetSuppliesInfoActionPerformed
        // TODO add your handling code here:
        if (! enterprise.fetchGroceryStockList()) {
            JOptionPane.showMessageDialog(this, "Cannot fetch data file from server ", "Warning",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (! enterprise.loadFreshGroceryStock()) {
            JOptionPane.showMessageDialog(this, "Failed to load complete Data from xontainers ", "Warning",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        populateTable();
        JOptionPane.showMessageDialog(this, "Latest Grocery Supplies list is fetched successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnGetSuppliesInfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelItem;
    private javax.swing.JButton btnGetSuppliesInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblGrocery;
    private javax.swing.JTextField txtItemDesc;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables
}
